version: 0.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "HERE" # taskdef-arn
      LoadBalancerInfo:
        ContainerName: "HERE" # container-name
        ContainerPort: HERE # container-port
      PlatformVersion: "LATEST"
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: ["HERE", "HERE", "HERE"] # network-info subnetsID
          SecurityGroups: ["HERE"]  # network-info SecurityGroupID
          AssignPublicIp: "DISABLED"
